- apiVersion: v1
  kind: Service
  metadata:
    name: flask-svc
    namespace: default
  spec:
    ports:
      - port: 5000
    selector:
      app: flask-svc
---
- apiVersion: v1
  kind: Service
  metadata:
    name: next-ui
    namespace: default
  spec:
    type: LoadBalancer
    ports:
      - port: 3000
    selector:
      app: next-ui