name: Build - Publish - Deploy PasteBin Clone

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for Service
        run: |
          ls -la
          cd flask-svc
          ls -la
          echo "docker build -f ./Dockerfile -t saadahm/flask-svc:$GITHUB_RUN_NUMBER ."
          docker build -f ./Dockerfile -t saadahm/flask-svc:$GITHUB_RUN_NUMBER .

      - name: Build Docker image for UI
        run: |
          ls -la
          cd next-ui
          ls -la
          echo "docker build -f ./Dockerfile -t saadahm/next-ui:$GITHUB_RUN_NUMBER ."
          docker build -f ./Dockerfile -t saadahm/next-ui:$GITHUB_RUN_NUMBER .

      - name: Publish Svc Docker image to ACR
        run: |
          echo "docker push saadahm/flask-svc:$GITHUB_RUN_NUMBER"
          docker push saadahm/flask-svc:$GITHUB_RUN_NUMBER
      
      - name: Publish UI Docker image to ACR
        run: |
          echo "docker push saadahm/next-ui:$GITHUB_RUN_NUMBER"
          docker push saadahm/next-ui:$GITHUB_RUN_NUMBER

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login Azure Kubernetes Service
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Test AKS
        run: |
          echo "kubectl auth can-i get namespaces"
          kubectl auth can-i get namespaces
          echo "kubectl auth can-i get pods --namespace default"
          kubectl auth can-i get pods --namespace default
          echo "kubectl get namespaces"
          kubectl get namespaces
          echo "kubectl get pods --namespace azure-vote"
          kubectl get pods --namespace azure-vote
          echo "kubectl get pods --namespace default"
          kubectl get pods --namespace default

      - name: Edit image tag in manifest
        run: |
          ls -la
          cd manifests
          ls -la
          echo "sed-ing"
          sed -i "s|{{UI_IMAGE_TAG}}|$GITHUB_RUN_NUMBER|g" deployment.yaml
          sed -i "s|{{SVC_IMAGE_TAG}}|$GITHUB_RUN_NUMBER|g" deployment.yaml
          echo "Show file"
          more deployment.yaml

      - name: Deploy to AKS
        run: |
          echo "kubectl apply -f ./manifests"
          kubectl apply -f ./manifests
