name: Build - Publish - Deploy PasteBin Clone UI

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Build Docker image
  #       run: |
  #         ls -la
  #         cd flask-svc
  #         ls -la
  #         echo "docker build -f ./Dockerfile -t ${{ secrets.REGISTRY_URL }}/pastebin-clone/flask-svc:$GITHUB_RUN_NUMBER ."
  #         docker build -f ./Dockerfile -t ${{ secrets.REGISTRY_URL }}/pastebin-clone/flask-svc:$GITHUB_RUN_NUMBER .

  #     - name: Log in Azure Container Registry
  #       run: |
  #         echo "az acr login --name ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USR }} --password ${{ secrets.REGISTRY_PWD }}"
  #         az acr login --name ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USR }} --password ${{ secrets.REGISTRY_PWD }}

  #     - name: Publish Docker image to ACR
  #       run: |
  #         echo "docker push ${{ secrets.REGISTRY_URL }}/pastebin-clone/flask-svc:$GITHUB_RUN_NUMBER"
  #         docker push ${{ secrets.REGISTRY_URL }}/pastebin-clone/flask-svc:$GITHUB_RUN_NUMBER

  deploy:
    runs-on: ubuntu-latest
    # needs: build

    steps:
      - name: Log in ACR
        run: |
          echo "az acr login --name ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USR }} --password ${{ secrets.REGISTRY_PWD }}"
          az acr login --name ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USR }} --password ${{ secrets.REGISTRY_PWD }}

      - name: Login Azure Kubernetes Service
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Test AKS
        run: |
          echo "kubectl auth can-i get namespaces"
          kubectl auth can-i get namespaces
          echo "kubectl auth can-i get pods --namespace default"
          kubectl auth can-i get pods --namespace default
          echo "kubectl get namespaces"
          kubectl get namespaces
          echo "kubectl get pods --namespace azure-vote"
          kubectl get pods --namespace azure-vote
          echo "kubectl get pods --namespace default"
          kubectl get pods --namespace default

      # - name: Deploy to AKS
      #   run: |
      #     echo "kubectl set image deployment/flask-svc pastebinSvc=${{ secrets.REGISTRY_URL }}/pastebin-clone/flask-svc:$GITHUB_RUN_NUMBER"
      #     kubectl set image deployment/flask-svc pastebinSvc=${{ secrets.REGISTRY_URL }}/pastebin-clone/flask-svc:6
